### PR TITLE
SHOT-3930: Refresh button

### PR DESCRIPTION
**Pull request by staceyoue**
* Add refresh button to top right title bar

### CODE REVIEW

**Comment by staceyoue** [comment]
Closing until underlying refresh issue addressed.

**Review by julien-lang — COMMENTED** [review]
We already had a refresh function but did not have a UI to trigger it?

**Comment by staceyoue** [comment]
> We already had a refresh function but did not have a UI to trigger it?

@julien-lang there is a "Refresh" action in the menu that uses this refresh function currently. The refresh action is not very visible in the menu (some users do not know about it) and requires an extra click, which is why we got a customer request to add this button.

**Review by carlos-villavicencio-adsk — APPROVED** [review]
LGTM

**Review by julien-lang — APPROVED** [review]
LGTM!

**Pull request merged**
